services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - .:/fastapi-app
    env_file:
      - .env
    restart: unless-stopped
